### ISSUE TITLE
Account confirmation email: HTML and text versions do not say the same thing

### ISSUE THREAD

**Issue by MaximeMaW** [re-figure/refigure#18]
Hi,

When I created my refigure account, the TEXT part of the email says:

> You have registered for the Refigure service, Please contact support@refigure.org to confirm registration.

Whereas the HTML part says:

>  Dear ***
> You have registered for the reFigure service. Please [click here]() to complete registration.
>
> Sincerely,
> The reFigure team. 

Is there a reason for such discrepancy? Additionally, I was confused because my email client shows the TEXT part of the body, and I thought that I had to email to finally get my account activated.

Thanks a lot!

**Comment by gg927** [comment]
We will rectify this. Thank you for bringing it to our attention.

**Comment by MaximeMaW** [comment]
Aweome, thanks!
